-- SIGPI PostgreSQL: esquema inicial idempotente. No borra información.
CREATE TABLE IF NOT EXISTS app_users (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  full_name varchar(255) NOT NULL CHECK (length(trim(full_name))>0),
  username varchar(255) NOT NULL UNIQUE,
  password varchar(255) NOT NULL,
  email varchar(255),
  role varchar(255) NOT NULL CHECK (role IN ('Administrador','Ventas','Almacén','Supervisor')),
  active boolean NOT NULL DEFAULT true,
  last_access timestamp(6)
);

CREATE TABLE IF NOT EXISTS categories (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code varchar(255) NOT NULL UNIQUE,
  name varchar(255) NOT NULL CHECK (length(trim(name))>0),
  description varchar(255),
  active boolean NOT NULL DEFAULT true
);

CREATE TABLE IF NOT EXISTS clients (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code varchar(255) NOT NULL UNIQUE,
  document_type varchar(255) NOT NULL CHECK (document_type IN ('RUC','DNI','CE')),
  document_number varchar(255) NOT NULL,
  name varchar(255) NOT NULL CHECK (length(trim(name))>0),
  address varchar(255),
  district varchar(255),
  province varchar(255),
  department varchar(255),
  phone varchar(255),
  email varchar(255),
  active boolean NOT NULL DEFAULT true,
  CHECK ((document_type='RUC' AND document_number ~ '^[0-9]{11}$') OR (document_type='DNI' AND document_number ~ '^[0-9]{8}$') OR (document_type='CE' AND length(trim(document_number))>0)),
  UNIQUE(document_type,document_number)
);

CREATE TABLE IF NOT EXISTS providers (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code varchar(255) NOT NULL UNIQUE,
  ruc varchar(255),
  business_name varchar(255) NOT NULL CHECK (length(trim(business_name))>0),
  contact varchar(255),
  phone varchar(255),
  email varchar(255),
  active boolean NOT NULL DEFAULT true
);

CREATE TABLE IF NOT EXISTS company_settings (
  id bigint PRIMARY KEY CHECK (id=1),
  business_name varchar(255) NOT NULL CHECK (length(trim(business_name))>0),
  ruc varchar(255),
  address varchar(255),
  branch varchar(255),
  phone varchar(255),
  email varchar(255),
  system_name varchar(255),
  version varchar(255)
);

CREATE TABLE IF NOT EXISTS products (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code varchar(255) NOT NULL UNIQUE,
  name varchar(255) NOT NULL CHECK (length(trim(name))>0),
  description varchar(255),
  category_id bigint NOT NULL REFERENCES categories(id),
  unit varchar(255),
  purchase_price numeric(12,2) NOT NULL DEFAULT 0 CHECK (purchase_price>=0),
  sale_price numeric(12,2) NOT NULL DEFAULT 0 CHECK (sale_price>=0),
  stock integer NOT NULL DEFAULT 0 CHECK (stock>=0),
  min_stock integer NOT NULL DEFAULT 0 CHECK (min_stock>=0),
  active boolean NOT NULL DEFAULT true
);

CREATE TABLE IF NOT EXISTS sales_orders (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code varchar(255) NOT NULL UNIQUE,
  client_id bigint NOT NULL REFERENCES clients(id),
  order_date date NOT NULL DEFAULT CURRENT_DATE,
  status varchar(255) NOT NULL CHECK (status IN ('Pendiente','En proceso','Preparado','Entregado','Cancelado')),
  total numeric(12,2) NOT NULL DEFAULT 0 CHECK (total>=0),
  responsible varchar(255)
);

CREATE TABLE IF NOT EXISTS order_items (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id bigint NOT NULL REFERENCES sales_orders(id),
  product_id bigint NOT NULL REFERENCES products(id),
  quantity integer NOT NULL DEFAULT 0 CHECK (quantity>0),
  price numeric(12,2) NOT NULL DEFAULT 0 CHECK (price>=0),
  subtotal numeric(12,2) NOT NULL DEFAULT 0 CHECK (subtotal>=0),
  UNIQUE(order_id,product_id)
);

CREATE TABLE IF NOT EXISTS inventory_movements (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  date date NOT NULL DEFAULT CURRENT_DATE,
  product_id bigint NOT NULL REFERENCES products(id),
  type varchar(255) NOT NULL CHECK (type IN ('ENTRADA','SALIDA')),
  quantity integer NOT NULL DEFAULT 0 CHECK (quantity>0),
  resulting_stock integer NOT NULL DEFAULT 0 CHECK (resulting_stock>=0),
  document varchar(255),
  responsible varchar(255),
  note varchar(255),
  provider_id bigint REFERENCES providers(id)
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_username_lower ON app_users(lower(username));
CREATE INDEX IF NOT EXISTS ix_products_category_id ON products(category_id);
CREATE INDEX IF NOT EXISTS ix_sales_orders_client_id ON sales_orders(client_id);
CREATE INDEX IF NOT EXISTS ix_sales_orders_order_date_status ON sales_orders(order_date,status);
CREATE INDEX IF NOT EXISTS ix_order_items_order_id ON order_items(order_id);
CREATE INDEX IF NOT EXISTS ix_order_items_product_id ON order_items(product_id);
CREATE INDEX IF NOT EXISTS ix_inventory_movements_product_id ON inventory_movements(product_id);
CREATE INDEX IF NOT EXISTS ix_inventory_movements_date ON inventory_movements(date);
CREATE INDEX IF NOT EXISTS ix_clients_document_number ON clients(document_number);
CREATE INDEX IF NOT EXISTS ix_movements_provider ON inventory_movements(provider_id);

-- Version 3: align with APF1 scope; preserve existing records.
ALTER TABLE company_settings ADD COLUMN IF NOT EXISTS default_min_stock integer NOT NULL DEFAULT 10;
ALTER TABLE company_settings ADD COLUMN IF NOT EXISTS low_stock_alerts boolean NOT NULL DEFAULT true;
ALTER TABLE company_settings ADD COLUMN IF NOT EXISTS session_minutes integer NOT NULL DEFAULT 30;
ALTER TABLE company_settings ADD COLUMN IF NOT EXISTS default_role varchar(255) NOT NULL DEFAULT 'Ventas';
ALTER TABLE sales_orders DROP CONSTRAINT IF EXISTS sales_orders_status_check;
ALTER TABLE sales_orders ADD CONSTRAINT sales_orders_status_check CHECK(status IN ('Pendiente','En proceso','Preparado','Enviado','Entregado','Cancelado'));
CREATE TABLE IF NOT EXISTS order_status_events (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 order_id bigint NOT NULL REFERENCES sales_orders(id),
 status varchar(255) NOT NULL,
 changed_at timestamp(6) NOT NULL,
 responsible varchar(255),
 note varchar(255)
);
CREATE INDEX IF NOT EXISTS ix_order_status_events_order ON order_status_events(order_id,changed_at);
INSERT INTO order_status_events(order_id,status,changed_at,responsible,note)
 SELECT o.id,o.status,CURRENT_TIMESTAMP,o.responsible,'Estado existente al actualizar versión; no se dispone del historial anterior'
 FROM sales_orders o WHERE NOT EXISTS(SELECT 1 FROM order_status_events h WHERE h.order_id=o.id);
CREATE TABLE IF NOT EXISTS order_drafts (
 user_id bigint PRIMARY KEY REFERENCES app_users(id) ON DELETE CASCADE,
 content text NOT NULL,
 updated_at timestamp(6) NOT NULL
);
CREATE TABLE IF NOT EXISTS demo_batches (code varchar(100) PRIMARY KEY,created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP);

CREATE SEQUENCE IF NOT EXISTS sales_order_code_seq START WITH 1000;
SELECT setval('sales_order_code_seq',GREATEST((SELECT last_value FROM sales_order_code_seq),COALESCE((SELECT MAX(substring(code from '([0-9]+)$')::bigint) FROM sales_orders WHERE code ~ '^PED-[0-9]{4}-[0-9]{1,9}$'),1000)),true);
