# Activar solo en el servicio Cloud: SPRING_PROFILES_ACTIVE=cloud
server.address=0.0.0.0
server.forward-headers-strategy=framework
server.servlet.session.cookie.secure=true
spring.thymeleaf.cache=true
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=1
