package pe.edu.utp.sigpi.controller;
import org.springframework.stereotype.Controller;import org.springframework.web.bind.annotation.*;import org.springframework.format.annotation.DateTimeFormat;import org.springframework.http.ResponseEntity;import jakarta.servlet.http.HttpServletRequest;
import pe.edu.utp.sigpi.repository.*;import pe.edu.utp.sigpi.service.*;import java.util.*;import java.time.LocalDate;
@Controller
public class ListingExports {
 private final ProductRepository products;private final ClientRepository clients;private final ProviderRepository providers;private final MovementRepository movements;private final SalesOrderRepository orders;
 public ListingExports(ProductRepository p,ClientRepository c,ProviderRepository v,MovementRepository m,SalesOrderRepository o){products=p;clients=c;providers=v;movements=m;orders=o;}
 @GetMapping({"/products/export.xlsx","/products/export.pdf","/inventory/export.xlsx","/inventory/export.pdf","/clients/export.xlsx","/clients/export.pdf","/providers/export.xlsx","/providers/export.pdf","/orders/export.xlsx","/orders/export.pdf","/movements/export.xlsx","/movements/export.pdf"})
 public ResponseEntity<byte[]> export(HttpServletRequest request,@RequestParam(defaultValue="")String q,@RequestParam(defaultValue="")String status,@RequestParam(defaultValue="")String type,@RequestParam(required=false)Long categoryId,@RequestParam(required=false)@DateTimeFormat(iso=DateTimeFormat.ISO.DATE)LocalDate from,@RequestParam(required=false)@DateTimeFormat(iso=DateTimeFormat.ISO.DATE)LocalDate to)throws java.io.IOException{
  if(from!=null&&to!=null&&from.isAfter(to))throw new IllegalArgumentException("Rango de fechas inválido");String area=request.getRequestURI().substring(request.getContextPath().length()).split("/")[1];String search=q.toLowerCase(Locale.ROOT);List<List<Object>> rows=new ArrayList<>();List<String> headers;
  switch(area){case "products":case "inventory":headers=List.of("Código","Producto","Categoría","Unidad","Compra","Venta","Stock","Mínimo","Estado");for(var p:products.findAll())if((p.getName()+p.getCode()).toLowerCase(Locale.ROOT).contains(search)&&(categoryId==null||p.getCategory().getId().equals(categoryId))&&(status.isBlank()||status.equals(p.getStockStatus())||status.equals("Alerta")&&p.isActive()&&p.getStock()<=p.getMinStock())&&(!area.equals("inventory")||p.isActive()))rows.add(Arrays.asList(p.getCode(),p.getName(),p.getCategory().getName(),p.getUnit(),p.getPurchasePrice(),p.getSalePrice(),p.getStock(),p.getMinStock(),p.getStockStatus()));break;
  case "clients":headers=List.of("Código","Documento","Cliente","Dirección","Teléfono","Correo","Estado");for(var c:clients.findAll())if((c.getName()+c.getDocumentNumber()).toLowerCase(Locale.ROOT).contains(search))rows.add(Arrays.asList(c.getCode(),c.getDocumentNumber(),c.getName(),c.getAddress(),c.getPhone(),c.getEmail(),c.isActive()?"Activo":"Inactivo"));break;
  case "providers":headers=List.of("Código","RUC","Proveedor","Contacto","Teléfono","Correo","Estado");for(var p:providers.findAll())if((p.getBusinessName()+p.getRuc()).toLowerCase(Locale.ROOT).contains(search))rows.add(Arrays.asList(p.getCode(),p.getRuc(),p.getBusinessName(),p.getContact(),p.getPhone(),p.getEmail(),p.isActive()?"Activo":"Inactivo"));break;
  case "orders":headers=List.of("Pedido","Fecha","Cliente","Estado","Responsable","Total");for(var o:orders.findAllByOrderByOrderDateDescIdDesc())if((o.getCode()+o.getClient().getName()).toLowerCase(Locale.ROOT).contains(search)&&(from==null||!o.getOrderDate().isBefore(from))&&(to==null||!o.getOrderDate().isAfter(to))&&(status.isBlank()||o.getStatus().equals(status)))rows.add(Arrays.asList(o.getCode(),o.getOrderDate(),o.getClient().getName(),o.getStatus(),o.getResponsible(),o.getTotal()));break;
  default:headers=List.of("Fecha","Código","Producto","Tipo","Cantidad","Stock","Documento","Responsable","Proveedor");for(var m:movements.findAllByOrderByDateDescIdDesc())if(m.getProduct().getName().toLowerCase(Locale.ROOT).contains(search)&&(from==null||!m.getDate().isBefore(from))&&(to==null||!m.getDate().isAfter(to))&&(type.isBlank()||m.getType().equals(type)))rows.add(Arrays.asList(m.getDate(),m.getProduct().getCode(),m.getProduct().getName(),m.getType(),m.getQuantity(),m.getResultingStock(),m.getDocument(),m.getResponsible(),m.getProvider()==null?"—":m.getProvider().getBusinessName()));}
  return Downloads.table(new ReportTable("SIGPI · "+area,headers,rows,rows.size()+" registros · Filtros de la consulta"),request.getRequestURI().endsWith(".pdf")?"pdf":"xlsx",area+"_sigpi");
 }
}
